[general]
import = ["~/.config/alacritty/colors.toml"]

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
size = 12.0

[window]
decorations = "none"
opacity = 0.85

[window.dimensions]
columns = 100
lines = 24

[window.padding]
x = 20
y = 20
